# Generated by Django 5.2.12 on 2026-03-25 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_auditor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'auditor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_data_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
